spring.application.name=nvuc
spring.datasource.url=jdbc:postgresql://localhost:5432/nvuc_db
spring.datasource.username=nvucuser
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

journal.files.path=D:/Projects/files