spring.application.name=nvuc

spring.datasource.url=${DB_url}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
journal.files.path=${PDF_STORAGE_PATH}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=false

spring.thymeleaf.cache=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8

logging.level.org.springframework.security=DEBUG