spring.application.name=nvuc

spring.datasource.url=${DB_url}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.thymeleaf.cache=false

journal.files.path=/opt/nvuc/files/

spring.messages.basename=messages
spring.messages.encoding=UTF-8