-- Additive migration: existing journal rows and identifiers are preserved.
CREATE TABLE IF NOT EXISTS journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER,
    issue VARCHAR(255),
    title VARCHAR(255),
    title_en VARCHAR(255),
    contents TEXT,
    contents_en TEXT,
    description TEXT,
    description_en TEXT,
    cover VARCHAR(255),
    pdf VARCHAR(255)
);
